включи свет:
- led_on свет включен
выключи свет:
- led_off свет выключен
запусти сервак:
- ssh_connect введи домен 
запусти браузер:
- browser запускаю браузер
интернет открой:
- browser открываю браузер
открой браузер:
- browser интернет активирован
покажи список:
- show_list_device вот список устройств
посмотреть фильм:
- browser сейчас открою браузер
работаешь:
- passive не найден

